fragment ManifestParts on Manifest {
  __typename
  subjects {
    __typename
    id
    title
    topics {
      __typename
      id
      title
      description
      image
      lessons {
        __typename
        id
        title
        description
        image
        tags
        createdDate
        lastUpdated
      }
    }
  }
}

fragment ArticleParts on Article {
  __typename
  title
  subject
  topic
  createdDate
  lastUpdated
  religion
  dimension
  comparison_tags
  quote {
    __typename
    text
    source
    reference
  }
  fact
  tags
  content {
    __typename
    ... on ArticleContentText {
      content
    }
    ... on ArticleContentImage {
      src
      caption
      alt
    }
    ... on ArticleContentHeader {
      text
    }
    ... on ArticleContentList {
      items
    }
    ... on ArticleContentComponent {
      name
      props {
        __typename
        content
        questions {
          __typename
          question
          options
          answer
          explanation
        }
      }
    }
  }
}

fragment ReligionParts on Religion {
  __typename
  name
  color
  icon
  dimensions {
    __typename
    ritual
    narrative
    experiential
    social
    ethical
    doctrinal
    material
  }
}

fragment ConceptsParts on Concepts {
  __typename
  term
  definition
  subject
  topic
  relatedArticle {
    ... on Article {
      __typename
      title
      subject
      topic
      createdDate
      lastUpdated
      religion
      dimension
      comparison_tags
      quote {
        __typename
        text
        source
        reference
      }
      fact
      tags
      content {
        __typename
        ... on ArticleContentText {
          content
        }
        ... on ArticleContentImage {
          src
          caption
          alt
        }
        ... on ArticleContentHeader {
          text
        }
        ... on ArticleContentList {
          items
        }
        ... on ArticleContentComponent {
          name
          props {
            __typename
            content
            questions {
              __typename
              question
              options
              answer
              explanation
            }
          }
        }
      }
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  tags
}

fragment ScannerConfigParts on ScannerConfig {
  __typename
  ignoredTerms
}
