fragment ManifestParts on Manifest {
  __typename
  subjects {
    __typename
    id
    title
    topics {
      __typename
      id
      title
      description
      image
      lessons {
        __typename
        id
        title
        description
        image
        tags
      }
    }
  }
}

fragment ArticleParts on Article {
  __typename
  title
  subject
  topic
  religion {
    ... on Religion {
      __typename
      name
      color
      icon
      dimensions {
        __typename
        ritual
        narrative
        experiential
        social
        ethical
        doctrinal
        material
      }
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  dimension
  comparison_tags
  fact
  tags
  content {
    __typename
    ... on ArticleContentText {
      content
    }
    ... on ArticleContentImage {
      src
      caption
      alt
    }
    ... on ArticleContentComponent {
      name
      props {
        __typename
        content
        questions {
          __typename
          question
          options
          answer
          explanation
        }
      }
    }
  }
}

fragment ReligionParts on Religion {
  __typename
  name
  color
  icon
  dimensions {
    __typename
    ritual
    narrative
    experiential
    social
    ethical
    doctrinal
    material
  }
}
