//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  manifest: Manifest;
  manifestConnection: ManifestConnection;
  article: Article;
  articleConnection: ArticleConnection;
  religion: Religion;
  religionConnection: ReligionConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryManifestArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryManifestConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ManifestFilter>;
};


export type QueryArticleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticleFilter>;
};


export type QueryReligionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReligionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReligionFilter>;
};

export type DocumentFilter = {
  manifest?: InputMaybe<ManifestFilter>;
  article?: InputMaybe<ArticleFilter>;
  religion?: InputMaybe<ReligionFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Manifest | Article | Religion | Folder;

export type ManifestSubjectsTopicsLessons = {
  __typename?: 'ManifestSubjectsTopicsLessons';
  id?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  createdDate?: Maybe<Scalars['String']['output']>;
  lastUpdated?: Maybe<Scalars['String']['output']>;
};

export type ManifestSubjectsTopics = {
  __typename?: 'ManifestSubjectsTopics';
  id?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  lessons?: Maybe<Array<Maybe<ManifestSubjectsTopicsLessons>>>;
};

export type ManifestSubjects = {
  __typename?: 'ManifestSubjects';
  id?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  topics?: Maybe<Array<Maybe<ManifestSubjectsTopics>>>;
};

export type Manifest = Node & Document & {
  __typename?: 'Manifest';
  subjects?: Maybe<Array<Maybe<ManifestSubjects>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ManifestSubjectsTopicsLessonsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  createdDate?: InputMaybe<DatetimeFilter>;
  lastUpdated?: InputMaybe<DatetimeFilter>;
};

export type ManifestSubjectsTopicsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  lessons?: InputMaybe<ManifestSubjectsTopicsLessonsFilter>;
};

export type ManifestSubjectsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  topics?: InputMaybe<ManifestSubjectsTopicsFilter>;
};

export type ManifestFilter = {
  subjects?: InputMaybe<ManifestSubjectsFilter>;
};

export type ManifestConnectionEdges = {
  __typename?: 'ManifestConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Manifest>;
};

export type ManifestConnection = Connection & {
  __typename?: 'ManifestConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ManifestConnectionEdges>>>;
};

export type ArticleContentText = {
  __typename?: 'ArticleContentText';
  content?: Maybe<Scalars['String']['output']>;
};

export type ArticleContentImage = {
  __typename?: 'ArticleContentImage';
  src?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type ArticleContentHeader = {
  __typename?: 'ArticleContentHeader';
  text?: Maybe<Scalars['String']['output']>;
};

export type ArticleContentList = {
  __typename?: 'ArticleContentList';
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ArticleContentComponentPropsQuestions = {
  __typename?: 'ArticleContentComponentPropsQuestions';
  question?: Maybe<Scalars['String']['output']>;
  options?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  answer?: Maybe<Scalars['String']['output']>;
  explanation?: Maybe<Scalars['String']['output']>;
};

export type ArticleContentComponentProps = {
  __typename?: 'ArticleContentComponentProps';
  content?: Maybe<Scalars['String']['output']>;
  questions?: Maybe<Array<Maybe<ArticleContentComponentPropsQuestions>>>;
};

export type ArticleContentComponent = {
  __typename?: 'ArticleContentComponent';
  name?: Maybe<Scalars['String']['output']>;
  props?: Maybe<ArticleContentComponentProps>;
};

export type ArticleContent = ArticleContentText | ArticleContentImage | ArticleContentHeader | ArticleContentList | ArticleContentComponent;

export type Article = Node & Document & {
  __typename?: 'Article';
  title?: Maybe<Scalars['String']['output']>;
  subject?: Maybe<Scalars['String']['output']>;
  topic?: Maybe<Scalars['String']['output']>;
  createdDate?: Maybe<Scalars['String']['output']>;
  lastUpdated?: Maybe<Scalars['String']['output']>;
  religion?: Maybe<Scalars['String']['output']>;
  dimension?: Maybe<Scalars['String']['output']>;
  comparison_tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  fact?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  content?: Maybe<Array<Maybe<ArticleContent>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ArticleContentTextFilter = {
  content?: InputMaybe<StringFilter>;
};

export type ArticleContentImageFilter = {
  src?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type ArticleContentHeaderFilter = {
  text?: InputMaybe<StringFilter>;
};

export type ArticleContentListFilter = {
  items?: InputMaybe<StringFilter>;
};

export type ArticleContentComponentPropsQuestionsFilter = {
  question?: InputMaybe<StringFilter>;
  options?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
  explanation?: InputMaybe<StringFilter>;
};

export type ArticleContentComponentPropsFilter = {
  content?: InputMaybe<StringFilter>;
  questions?: InputMaybe<ArticleContentComponentPropsQuestionsFilter>;
};

export type ArticleContentComponentFilter = {
  name?: InputMaybe<StringFilter>;
  props?: InputMaybe<ArticleContentComponentPropsFilter>;
};

export type ArticleContentFilter = {
  text?: InputMaybe<ArticleContentTextFilter>;
  image?: InputMaybe<ArticleContentImageFilter>;
  header?: InputMaybe<ArticleContentHeaderFilter>;
  list?: InputMaybe<ArticleContentListFilter>;
  component?: InputMaybe<ArticleContentComponentFilter>;
};

export type ArticleFilter = {
  title?: InputMaybe<StringFilter>;
  subject?: InputMaybe<StringFilter>;
  topic?: InputMaybe<StringFilter>;
  createdDate?: InputMaybe<DatetimeFilter>;
  lastUpdated?: InputMaybe<DatetimeFilter>;
  religion?: InputMaybe<StringFilter>;
  dimension?: InputMaybe<StringFilter>;
  comparison_tags?: InputMaybe<StringFilter>;
  fact?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  content?: InputMaybe<ArticleContentFilter>;
};

export type ArticleConnectionEdges = {
  __typename?: 'ArticleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Article>;
};

export type ArticleConnection = Connection & {
  __typename?: 'ArticleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArticleConnectionEdges>>>;
};

export type ReligionDimensions = {
  __typename?: 'ReligionDimensions';
  ritual?: Maybe<Scalars['JSON']['output']>;
  narrative?: Maybe<Scalars['JSON']['output']>;
  experiential?: Maybe<Scalars['JSON']['output']>;
  social?: Maybe<Scalars['JSON']['output']>;
  ethical?: Maybe<Scalars['JSON']['output']>;
  doctrinal?: Maybe<Scalars['JSON']['output']>;
  material?: Maybe<Scalars['JSON']['output']>;
};

export type Religion = Node & Document & {
  __typename?: 'Religion';
  name: Scalars['String']['output'];
  color?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  dimensions?: Maybe<ReligionDimensions>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ReligionDimensionsFilter = {
  ritual?: InputMaybe<RichTextFilter>;
  narrative?: InputMaybe<RichTextFilter>;
  experiential?: InputMaybe<RichTextFilter>;
  social?: InputMaybe<RichTextFilter>;
  ethical?: InputMaybe<RichTextFilter>;
  doctrinal?: InputMaybe<RichTextFilter>;
  material?: InputMaybe<RichTextFilter>;
};

export type ReligionFilter = {
  name?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
  icon?: InputMaybe<ImageFilter>;
  dimensions?: InputMaybe<ReligionDimensionsFilter>;
};

export type ReligionConnectionEdges = {
  __typename?: 'ReligionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Religion>;
};

export type ReligionConnection = Connection & {
  __typename?: 'ReligionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReligionConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateManifest: Manifest;
  createManifest: Manifest;
  updateArticle: Article;
  createArticle: Article;
  updateReligion: Religion;
  createReligion: Religion;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateManifestArgs = {
  relativePath: Scalars['String']['input'];
  params: ManifestMutation;
};


export type MutationCreateManifestArgs = {
  relativePath: Scalars['String']['input'];
  params: ManifestMutation;
};


export type MutationUpdateArticleArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticleMutation;
};


export type MutationCreateArticleArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticleMutation;
};


export type MutationUpdateReligionArgs = {
  relativePath: Scalars['String']['input'];
  params: ReligionMutation;
};


export type MutationCreateReligionArgs = {
  relativePath: Scalars['String']['input'];
  params: ReligionMutation;
};

export type DocumentUpdateMutation = {
  manifest?: InputMaybe<ManifestMutation>;
  article?: InputMaybe<ArticleMutation>;
  religion?: InputMaybe<ReligionMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  manifest?: InputMaybe<ManifestMutation>;
  article?: InputMaybe<ArticleMutation>;
  religion?: InputMaybe<ReligionMutation>;
};

export type ManifestSubjectsTopicsLessonsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  createdDate?: InputMaybe<Scalars['String']['input']>;
  lastUpdated?: InputMaybe<Scalars['String']['input']>;
};

export type ManifestSubjectsTopicsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  lessons?: InputMaybe<Array<InputMaybe<ManifestSubjectsTopicsLessonsMutation>>>;
};

export type ManifestSubjectsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  topics?: InputMaybe<Array<InputMaybe<ManifestSubjectsTopicsMutation>>>;
};

export type ManifestMutation = {
  subjects?: InputMaybe<Array<InputMaybe<ManifestSubjectsMutation>>>;
};

export type ArticleContentTextMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type ArticleContentImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type ArticleContentHeaderMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type ArticleContentListMutation = {
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ArticleContentComponentPropsQuestionsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  options?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  answer?: InputMaybe<Scalars['String']['input']>;
  explanation?: InputMaybe<Scalars['String']['input']>;
};

export type ArticleContentComponentPropsMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
  questions?: InputMaybe<Array<InputMaybe<ArticleContentComponentPropsQuestionsMutation>>>;
};

export type ArticleContentComponentMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  props?: InputMaybe<ArticleContentComponentPropsMutation>;
};

export type ArticleContentMutation = {
  text?: InputMaybe<ArticleContentTextMutation>;
  image?: InputMaybe<ArticleContentImageMutation>;
  header?: InputMaybe<ArticleContentHeaderMutation>;
  list?: InputMaybe<ArticleContentListMutation>;
  component?: InputMaybe<ArticleContentComponentMutation>;
};

export type ArticleMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subject?: InputMaybe<Scalars['String']['input']>;
  topic?: InputMaybe<Scalars['String']['input']>;
  createdDate?: InputMaybe<Scalars['String']['input']>;
  lastUpdated?: InputMaybe<Scalars['String']['input']>;
  religion?: InputMaybe<Scalars['String']['input']>;
  dimension?: InputMaybe<Scalars['String']['input']>;
  comparison_tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  fact?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  content?: InputMaybe<Array<InputMaybe<ArticleContentMutation>>>;
};

export type ReligionDimensionsMutation = {
  ritual?: InputMaybe<Scalars['JSON']['input']>;
  narrative?: InputMaybe<Scalars['JSON']['input']>;
  experiential?: InputMaybe<Scalars['JSON']['input']>;
  social?: InputMaybe<Scalars['JSON']['input']>;
  ethical?: InputMaybe<Scalars['JSON']['input']>;
  doctrinal?: InputMaybe<Scalars['JSON']['input']>;
  material?: InputMaybe<Scalars['JSON']['input']>;
};

export type ReligionMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  dimensions?: InputMaybe<ReligionDimensionsMutation>;
};

export type ManifestPartsFragment = { __typename: 'Manifest', subjects?: Array<{ __typename: 'ManifestSubjects', id?: string | null, title?: string | null, topics?: Array<{ __typename: 'ManifestSubjectsTopics', id?: string | null, title?: string | null, description?: string | null, image?: string | null, lessons?: Array<{ __typename: 'ManifestSubjectsTopicsLessons', id?: string | null, title?: string | null, description?: string | null, image?: string | null, tags?: Array<string | null> | null, createdDate?: string | null, lastUpdated?: string | null } | null> | null } | null> | null } | null> | null };

export type ArticlePartsFragment = { __typename: 'Article', title?: string | null, subject?: string | null, topic?: string | null, createdDate?: string | null, lastUpdated?: string | null, religion?: string | null, dimension?: string | null, comparison_tags?: Array<string | null> | null, fact?: string | null, tags?: Array<string | null> | null, content?: Array<{ __typename: 'ArticleContentText', content?: string | null } | { __typename: 'ArticleContentImage', src?: string | null, caption?: string | null, alt?: string | null } | { __typename: 'ArticleContentHeader', text?: string | null } | { __typename: 'ArticleContentList', items?: Array<string | null> | null } | { __typename: 'ArticleContentComponent', name?: string | null, props?: { __typename: 'ArticleContentComponentProps', content?: string | null, questions?: Array<{ __typename: 'ArticleContentComponentPropsQuestions', question?: string | null, options?: Array<string | null> | null, answer?: string | null, explanation?: string | null } | null> | null } | null } | null> | null };

export type ReligionPartsFragment = { __typename: 'Religion', name: string, color?: string | null, icon?: string | null, dimensions?: { __typename: 'ReligionDimensions', ritual?: any | null, narrative?: any | null, experiential?: any | null, social?: any | null, ethical?: any | null, doctrinal?: any | null, material?: any | null } | null };

export type ManifestQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ManifestQuery = { __typename?: 'Query', manifest: { __typename: 'Manifest', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, subjects?: Array<{ __typename: 'ManifestSubjects', id?: string | null, title?: string | null, topics?: Array<{ __typename: 'ManifestSubjectsTopics', id?: string | null, title?: string | null, description?: string | null, image?: string | null, lessons?: Array<{ __typename: 'ManifestSubjectsTopicsLessons', id?: string | null, title?: string | null, description?: string | null, image?: string | null, tags?: Array<string | null> | null, createdDate?: string | null, lastUpdated?: string | null } | null> | null } | null> | null } | null> | null } };

export type ManifestConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ManifestFilter>;
}>;


export type ManifestConnectionQuery = { __typename?: 'Query', manifestConnection: { __typename?: 'ManifestConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ManifestConnectionEdges', cursor: string, node?: { __typename: 'Manifest', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, subjects?: Array<{ __typename: 'ManifestSubjects', id?: string | null, title?: string | null, topics?: Array<{ __typename: 'ManifestSubjectsTopics', id?: string | null, title?: string | null, description?: string | null, image?: string | null, lessons?: Array<{ __typename: 'ManifestSubjectsTopicsLessons', id?: string | null, title?: string | null, description?: string | null, image?: string | null, tags?: Array<string | null> | null, createdDate?: string | null, lastUpdated?: string | null } | null> | null } | null> | null } | null> | null } | null } | null> | null } };

export type ArticleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArticleQuery = { __typename?: 'Query', article: { __typename: 'Article', id: string, title?: string | null, subject?: string | null, topic?: string | null, createdDate?: string | null, lastUpdated?: string | null, religion?: string | null, dimension?: string | null, comparison_tags?: Array<string | null> | null, fact?: string | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, content?: Array<{ __typename: 'ArticleContentText', content?: string | null } | { __typename: 'ArticleContentImage', src?: string | null, caption?: string | null, alt?: string | null } | { __typename: 'ArticleContentHeader', text?: string | null } | { __typename: 'ArticleContentList', items?: Array<string | null> | null } | { __typename: 'ArticleContentComponent', name?: string | null, props?: { __typename: 'ArticleContentComponentProps', content?: string | null, questions?: Array<{ __typename: 'ArticleContentComponentPropsQuestions', question?: string | null, options?: Array<string | null> | null, answer?: string | null, explanation?: string | null } | null> | null } | null } | null> | null } };

export type ArticleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticleFilter>;
}>;


export type ArticleConnectionQuery = { __typename?: 'Query', articleConnection: { __typename?: 'ArticleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArticleConnectionEdges', cursor: string, node?: { __typename: 'Article', id: string, title?: string | null, subject?: string | null, topic?: string | null, createdDate?: string | null, lastUpdated?: string | null, religion?: string | null, dimension?: string | null, comparison_tags?: Array<string | null> | null, fact?: string | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, content?: Array<{ __typename: 'ArticleContentText', content?: string | null } | { __typename: 'ArticleContentImage', src?: string | null, caption?: string | null, alt?: string | null } | { __typename: 'ArticleContentHeader', text?: string | null } | { __typename: 'ArticleContentList', items?: Array<string | null> | null } | { __typename: 'ArticleContentComponent', name?: string | null, props?: { __typename: 'ArticleContentComponentProps', content?: string | null, questions?: Array<{ __typename: 'ArticleContentComponentPropsQuestions', question?: string | null, options?: Array<string | null> | null, answer?: string | null, explanation?: string | null } | null> | null } | null } | null> | null } | null } | null> | null } };

export type ReligionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReligionQuery = { __typename?: 'Query', religion: { __typename: 'Religion', id: string, name: string, color?: string | null, icon?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, dimensions?: { __typename: 'ReligionDimensions', ritual?: any | null, narrative?: any | null, experiential?: any | null, social?: any | null, ethical?: any | null, doctrinal?: any | null, material?: any | null } | null } };

export type ReligionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReligionFilter>;
}>;


export type ReligionConnectionQuery = { __typename?: 'Query', religionConnection: { __typename?: 'ReligionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReligionConnectionEdges', cursor: string, node?: { __typename: 'Religion', id: string, name: string, color?: string | null, icon?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, dimensions?: { __typename: 'ReligionDimensions', ritual?: any | null, narrative?: any | null, experiential?: any | null, social?: any | null, ethical?: any | null, doctrinal?: any | null, material?: any | null } | null } | null } | null> | null } };

export const ManifestPartsFragmentDoc = gql`
    fragment ManifestParts on Manifest {
  __typename
  subjects {
    __typename
    id
    title
    topics {
      __typename
      id
      title
      description
      image
      lessons {
        __typename
        id
        title
        description
        image
        tags
        createdDate
        lastUpdated
      }
    }
  }
}
    `;
export const ArticlePartsFragmentDoc = gql`
    fragment ArticleParts on Article {
  __typename
  title
  subject
  topic
  createdDate
  lastUpdated
  religion
  dimension
  comparison_tags
  fact
  tags
  content {
    __typename
    ... on ArticleContentText {
      content
    }
    ... on ArticleContentImage {
      src
      caption
      alt
    }
    ... on ArticleContentHeader {
      text
    }
    ... on ArticleContentList {
      items
    }
    ... on ArticleContentComponent {
      name
      props {
        __typename
        content
        questions {
          __typename
          question
          options
          answer
          explanation
        }
      }
    }
  }
}
    `;
export const ReligionPartsFragmentDoc = gql`
    fragment ReligionParts on Religion {
  __typename
  name
  color
  icon
  dimensions {
    __typename
    ritual
    narrative
    experiential
    social
    ethical
    doctrinal
    material
  }
}
    `;
export const ManifestDocument = gql`
    query manifest($relativePath: String!) {
  manifest(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ManifestParts
  }
}
    ${ManifestPartsFragmentDoc}`;
export const ManifestConnectionDocument = gql`
    query manifestConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ManifestFilter) {
  manifestConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ManifestParts
      }
    }
  }
}
    ${ManifestPartsFragmentDoc}`;
export const ArticleDocument = gql`
    query article($relativePath: String!) {
  article(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArticleParts
  }
}
    ${ArticlePartsFragmentDoc}`;
export const ArticleConnectionDocument = gql`
    query articleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArticleFilter) {
  articleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArticleParts
      }
    }
  }
}
    ${ArticlePartsFragmentDoc}`;
export const ReligionDocument = gql`
    query religion($relativePath: String!) {
  religion(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReligionParts
  }
}
    ${ReligionPartsFragmentDoc}`;
export const ReligionConnectionDocument = gql`
    query religionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReligionFilter) {
  religionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReligionParts
      }
    }
  }
}
    ${ReligionPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      manifest(variables: ManifestQueryVariables, options?: C): Promise<{data: ManifestQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ManifestQueryVariables, query: string}> {
        return requester<{data: ManifestQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ManifestQueryVariables, query: string}, ManifestQueryVariables>(ManifestDocument, variables, options);
      },
    manifestConnection(variables?: ManifestConnectionQueryVariables, options?: C): Promise<{data: ManifestConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ManifestConnectionQueryVariables, query: string}> {
        return requester<{data: ManifestConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ManifestConnectionQueryVariables, query: string}, ManifestConnectionQueryVariables>(ManifestConnectionDocument, variables, options);
      },
    article(variables: ArticleQueryVariables, options?: C): Promise<{data: ArticleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleQueryVariables, query: string}> {
        return requester<{data: ArticleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleQueryVariables, query: string}, ArticleQueryVariables>(ArticleDocument, variables, options);
      },
    articleConnection(variables?: ArticleConnectionQueryVariables, options?: C): Promise<{data: ArticleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleConnectionQueryVariables, query: string}> {
        return requester<{data: ArticleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleConnectionQueryVariables, query: string}, ArticleConnectionQueryVariables>(ArticleConnectionDocument, variables, options);
      },
    religion(variables: ReligionQueryVariables, options?: C): Promise<{data: ReligionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReligionQueryVariables, query: string}> {
        return requester<{data: ReligionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReligionQueryVariables, query: string}, ReligionQueryVariables>(ReligionDocument, variables, options);
      },
    religionConnection(variables?: ReligionConnectionQueryVariables, options?: C): Promise<{data: ReligionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReligionConnectionQueryVariables, query: string}> {
        return requester<{data: ReligionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReligionConnectionQueryVariables, query: string}, ReligionConnectionQueryVariables>(ReligionConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  